# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08534f5d8699e2ec897acc807217a2b33eb925f9fa4c55a9f016a82cf5a5be3851d742b6fabafeff56852fbb7300c55ffc77cdd9046c37f7c327fc1965a114e9

test:
  secret_key_base: 550903455e5feba540a8eaae61a16b983fa4c02b454b4ce4378c070eebb55bb64b981b8682994302d5034371a2ca2ea9a8dfd3593da5fb647d63a3860e49e902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
